sudo: required
dist: trusty
group: deprecated-2017Q4
language: bash
before_script:
- sudo apt-get update -qq
- sudo apt-get install aria2 zip unzip check -qq
script:
- source ./env.sh
- "${DLR} ${ROOTFS_URL} -o ${ROOTFS_FN}"
- "${DLR} ${FRTCP_URL} -o ${FRTCP_FN}"
- 
- sudo tar -zxpf ${ROOTFS_FN}
- cd root.x86_64
- sudo cp -bf ../mirrorlist ./etc/pacman.d/mirrorlist
- sudo cp -bf ../pacman.conf.nosig ./etc/pacman.conf
- sudo sed -i -e "s/#en_US.UTF-8/en_US.UTF-8/" ./etc/locale.gen
- echo "LANG=en_US.UTF-8" | sudo tee ./etc/locale.conf
- sudo ln -sf /etc/locale.conf ./etc/default/locale
- sudo cp -f ../${FRTCP_FN} ./root/
- sudo cp -f /etc/resolv.conf ./etc/resolv.conf
- sudo mv -f ./etc/mtab ./etc/mtab.bak
- echo "rootfs / rootfs rw 0 0" | sudo tee ./etc/mtab
- 
- sudo mount -t proc proc proc/
- sudo mount --bind /sys sys
- 
- sudo chroot . /usr/bin/pacman -Syu --noconfirm ${PAC_PKGS}
- sudo chmod u+s ./usr/bin/ping
- sudo rm -rf ./etc/mtab
- echo "rootfs / rootfs rw 0 0" | sudo tee ./etc/mtab
- sudo chroot . /usr/bin/locale-gen
- yes | sudo chroot . /usr/bin/pacman -U --force /root/${FRTCP_FN}
- yes | sudo chroot . /usr/bin/pacman -Scc
- 
- sudo umount ./{sys,proc}
- sudo mv -f ./etc/mtab.bak ./etc/mtab
- sudo cp -f ../pacman.conf ./etc/pacman.conf
- echo "# This file was automatically generated by WSL. To stop automatic generation
  of this file, remove this line." | sudo tee ./etc/resolv.conf
- 
- sudo rm -rf `sudo find ./root/ -type f`
- sudo rm -rf `sudo find ./var/cache/pacman/pkg/ -type f`
- 
- sudo tar -zcpf ../rootfs.tar.gz *
- sudo chown `id -un` ../rootfs.tar.gz
- cd ..
notifications:
  email: false
deploy:
  provider: releases
  api_key:
    secure: FG5Kdbdwx6GnBe70oRYkEQxg7QNBMARwbWHv+RL1AsaL2IppfqhJiHerqfFsm5yjrHz/G+k8cdycyaZ4XsyIjazylgShjR+jx43hSoqnCSPCcBphSCbzmxSCXbgBiatuyvxam+6CroEGzf97OimS8p/7gMBtnbhyhWq3Ig1ntTdgZg4oZu2nhwvOymDsH8f8jJt/BA0Zs/aMUFCbI3KUtcEytM5HFJD8k/qOXTEkKd4VOMxX27ADStoHCp3OPQUK6uFvkMc0+TVXgVWricnETit6SXfO70MSzNOu5Os+w2tITt7tFSOmfgMr/0Fgplia8lsvY46SHjaODIwVOxK1VbrCjPyBHkGpWG9P1K9l8+F4CiGpJY72a0S0YWpg7HcGJOmmS0J4oFxtQB4ns3hyhhFzVb6koi+xlWRhBVV1yd74j2S7N6er5pFxaFAJjCidtV9z0pIq+Mp2Iguzyj62D1IP9KmVK134gLfivB41sKS9ayHY2AfOiIdX6WHsIJYSDJSlRj2gbpmcBy+X1JdPPTJ3L0tpKzBhNataAAObZc6Zu2hDZ3SOsJ1/aEWxkLfAfLshR08epCi/7CCy6fK277L7i60obfTVJDbhshmd2iVE5LwsGoG68tDQYuELdc4tQRtmvGEdHqViit2fT3vNyiuAW1NfLsRjBANgwewyr+A=
  file: rootfs.tar.gz
  on:
    repo: yuk7/ArchWSL-FS
    tags: true
    all_branches: true
skip_cleanup: true
