name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:
  compile:
    name: Compile rootfs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          make
          make clean